### ISSUE TITLE
Security Vulnerability: Insecure password hashing technique used

### ISSUE THREAD

**Issue by Cisien** [ClaudiuBrandusa/LoginRegister#1]
https://github.com/ClaudiuBrandusa/LoginRegister/blob/master/Encryption.cs

SHA1 without a seed (and even with a seed) is not an acceptable hashing algorithm for passwords. If the database was to be compromised, then all passwords hashed with this method would be vulnerable to rainbow-table lookups. 

https://www.bentasker.co.uk/blog/security/201-why-you-should-be-asking-how-your-passwords-are-stored

**Comment by ClaudiuBrandusa** [comment]
Thanks for the observation, i will take care of it.

**Comment by ClaudiuBrandusa** [comment]
Issue solved.
